account/urls.py
from django.urls import path
from django.conf.urls import include
from account import views


app_name='account'

urlpatterns = [
   
    path("signup/",views.signUp,name="signup"),
    path("login/",views.login,name="login"),
    path("registration/",views.registration,name="registration"),
    path('Logout/',views.Logout,name="logout"),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate_account, name='activate'),
  
]

onlinetutors/urls.py
from django.urls import path
from onlinetutors import views


app_name='onlinetutors'

urlpatterns = [
    
    path("",views.home,name='home'),
    path("Arts/",views.arts,name="Arts"),
    path(r'^(?P<category_slug>[-\w]+)/$', views.arts, name='arts'),
    path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.tutor_detail, name='tutor_detail'),
    path("tutorprofile/",views.profile,name="tutorprofile"),
    # path("registration/",views.registration,name="registration"),
    path("thankyou/",views.thankyou,name="thankyou"),
    path("checkout/",views.checkout,name="checkout"),
   
    path('add_comments/<int:pk>/',views.AddCommentView,name="add_comments"),
    path('ratings/',views.ratings,name="ratings"),
    path('datePicker',views.datePicker,name="datePicker"),
    # path(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.AddCommentView,name="add_comments"), 
   
    
    ]

searchtutor/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("",include('onlinetutors.urls')),
      
    path('account/',include('account.urls')),
    path('api_display/',include('api_display.urls')),
   
    path('admin/', admin.site.urls),
    
        
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name="reset_password"),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),name="password_reset_complete"),
   
    
    
]
urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/activate_account.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'account:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Find a tutor</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
    
    <link rel='stylesheet' type="text/css" href="{% static 'styles/base.css' %}"/>
   
    if home.html
    <link rel="stylesheet" href="{% static 'styles/home.css' %}"/>
    
    if Arts.html 
    <link rel="stylesheet" href="{% static 'styles/arts.css' %}"/>
    
    if detail.html
    <link rel="stylesheet" href="{% static 'styles/details.css' %}"/> 
    
    if tutorprofile.html 
    <link rel="stylesheet" href="{%static 'styles/tutorprofile.css' %}"/> 
    
    if registration.html 
    <link rel="stylesheet" href="{%static 'styles/registration.css' %}"/>
    
    if signup.html 
    <link rel="stylesheet" href="{%static 'styles/signup.css' %}"/>

    if login.html 
    <link rel="stylesheet" href="{%static 'styles/login.css' %}"/>

    if resetpassword.html 
    <link rel="stylesheet" href="{%static 'styles/resetpassword.css' %}" />

    if thankyou.html
    <link rel="stylesheet" href="{%static 'styles/thankyou.css' %}" />
</head>
<body>
    <div class='container-fluid'>
      
    
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
            <!-- Brand -->
            <a class="navbar-brand" href="#">Tutors</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <!-- Links -->
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "onlinetutors:tutorprofile" %}">Become an instructor</a>
              </li> 
          
              <!-- Dropdown -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                  Find a tutor
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">Music</a>
                  <a class="dropdown-item" href="#">Dance</a>
                  <a class="dropdown-item" href="#">Theatre</a>
                  <a class="dropdown-item" href="{% url "onlinetutors:Arts" %}">Arts</a>
                </div>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
              <li class="nav-item" style="color:white;margin-top:8px;">Hello {{user.username}}</li>
                <li class="nav-item">
                <a class="nav-link" href="{% url "account:logout" %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:login" %}">Login</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "account:signup" %}">SignUp</a>
                </li>
               
            </ul>
              </div>
          </nav>
    </div>
    {%block content%}


    {%endblock content%}
    <!-- <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script> -->
    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel='stylesheet' type="text/css" href="../static/styles/details.css"/>
   
    <title>Find a tutor</title>
</head>
<body>
    
    <div class='container-fluid'>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
            <!-- Brand -->
            <a class="navbar-brand" href="#">Tutors</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <!-- Links -->
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About Us</a>
              </li>
          
              <!-- Dropdown -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                  Find a tutor
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">Music</a>
                  <a class="dropdown-item" href="#">Dance</a>
                  <a class="dropdown-item" href="#">Theatre</a>
                  <a class="dropdown-item" href="{% url "onlinetutors:Arts" %}">Arts</a>
                </div>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Logout</a>
                </li>
            </ul>
              </div>
          </nav>
    </div>
    
  
   
<div class="container">
    <div class="sidenav">
       <div class="header">
           <p>$20/hr</p>
           <hr>
       </div>
       <div class="items">
           <ul class="extra_details">
           <li><p>No subscriptions or upfront payments</p></li>
           <li><p>Only pay for the time you need</p></li>
           <li><p>your first hour is free</p></li>
           </ul>
           <div class="checkout">
           <button type="button">Checkout</button>
           </div>
       </div>
       

    </div>
   
    <div class="head">
        <img class=" rounded-circle img-responsive"  src="../static/images/baby_1.jpg"/>
    <div class="taglines">
        <h4>Liya Anne</h4>
        <h3>Soprano Vocalist with a Bachelor in Professional Music</h3>
    </div>
    
    <div class="qualification">
        <h4>Qualifications for “Voice (Music)”</h4>
            
            <p>I graduated summa cum laude with a Bachelor in Professional Music from Berklee College Of Music. 
                I have studied classical theory and counterpoint I’m both Berklee College Of Music and University of Massachusetts Boston.
                At UMass I received a classical background in voice and music theory and at Berklee a contemporary and classical background in multiple fields, 
                such as performance, music theory, counterpoint, songwriting, music business, and more. I have always excelled in my music theory, counterpoint, 
                sight singing and reading classes and would love to help you get better as well!
            </p>
        <hr>
            <p>Related Subjects&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Liya has also tutored Voice (Music), Songwriting and 3 more subjects.</p>
        
    </div>
</div>
<div class="aboutme">
    <div class="name">
        <h4>About Me</h4>
        <hr>
    </div>
    <div class="row">
        <div class="col-3">
            <p>Bio</p>
        </div>
        <div class="col-9">
            <p id="aboutme">I’m Liya! I graduated summa cum laude with a Bachelor’s degree in Professional Music from 
                Berklee College Of Music. At Berklee I studied a mixture of Performance, 
                Songwriting and Music Business and took many other classes, 
                such as: Ear Training & Sight Singing, Counterpoint, Conducting, Music History, 
                Arrangement, etc. I also took part in songwriting and multiple music business clubs 
                and had the honor to represent the college at various industry trips in Nashville 
                and New York City. I am...</p>
                <a href="#more" id="show">More..</a>
                <p id="more">I have studied music theory, sight singing/reading and voice at both 
                    Berklee College Of Music and University of Massachusetts Boston. At UMass I 
                    received a classical training, whereas at Berklee I received a contemporary 
                    music education in those fields. Throughout my college years I have always excelled 
                    in my music theory courses and have been asked to help my peers by tutoring them in 
                    subjects such as music theory, solfege, counterpoint and have also offered voice 
                    lessons and beginning keyboard skills. I used to hold weekly meetings with my peers 
                    where I would help them with anything they didn't understand that was taught the
                     previous week. Music is a different language so a good tutor is very important!
                    The way I approach tutoring is seeing where the students' level is and breaking 
                    down the information, so they can understand it and going through that information 
                    as much as they need. I have a lot of theory, solfege, voice lesson and beginning piano 
                    books that are very helpful as well. Throughout my own studies I have found multiple ways 
                    to make music theory concepts more memorable and I love sharing those with students. 
                    I have tutored mainly peers and adults but also love teaching children. I believe that 
                    learning music is a wonderful thing, so I want to help you learn the theory behind your 
                    favorite song, and help you find your voice while encouraging a fun learning environment.

                    I am easy to reach, so do not hesita<a href="#more" id="hide">Read less</a></p>

                
                
                
        </div>
    </div>

<hr>
<div class="row">

    <div class="col-3 education">
        <p>Education</p>
    </div>
    <div class="col-9">
        <p>Berklee College of Music</p>
        <p>Professional Music</p>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-3 policies">
        policies
    </div>
    <div class="col-9">
        <p>Hourly Rate: $40</p>
        <p>Lesson cancellation: <strong>24 hours notice required</strong></p>
        <p>Your first lesson is backed by our Good Fit Guarantee</p>
    </div>

</div>
<hr>
<div class="row">
    <div class="col-3 policies">
        Schedule
    </div>
    <div class="col-2">
        
        <p>MON</p>
        <p>TUE</p>
        <p>WED</p>
        <p>THU</p>
        <p>FRI</p>
        <p>SAT</p>
        <p>SUN</p>

    </div>
    <div class="col-4">
        <p>5:00 am - 8:00 pm</p>
        <p>5:00 am - 8:00 pm</p>
        <p>5:00 am - 8:00 pm</p>
        <p>5:00 am - 8:00 pm</p>
        <p>5:00 am - 8:00 pm</p>
        <p>5:00 am - 8:00 pm</p>
        <p>5:00 am - 8:00 pm</p>
       
    </div>

</div>
<hr>
<div class="row">
    <div class="col-3 policies">
        Subjects
    </div>
    <div class="col-3">
        <p><strong>Home School</strong></p>
        <p>Piano</p>
        <p><strong>Language</strong></p>
        <p>English</p>
    </div>
    <div class="col-4">
        <p><strong>Most Popular</strong></p>
        <p>Piano</p>
        <p><strong>Music</strong></p>
        <p>Ear Training, Piano, Sight Singing, Songwriting, Voice (Music),</p>
        <p><strong>Summer</strong></p>
        <p>Piano</p>

    </div>

</div>
<h5><strong>Ratings and Reviews</strong></h5>
<hr>
<div class="row">
    <div class="col-3 ratings">
        <p>Rating</p>
    </div>
    <div class="col-9">
        <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star"></span>
        <div class="ratingsbar">
            <div class="flex">
                <b class="text-nowrap">5 star</b>
                <div class="rating-bar-container">
                    <span class="rating-bar" style="width:100.0%"></span>
                </div>
            </div>
            <div class="flex">
                <b class="text-nowrap">4 star</b>
                <div class="rating-bar-container">
                    <span class="rating-bar" style="width:100.0%"></span>
                </div>
            </div>
            <div class="flex">
                <b class="text-nowrap">3 star</b>
                <div class="rating-bar-container">
                    <span class="rating-bar" style="width:100.0%"></span>
                </div>
            </div>
            <div class="flex">
                <b class="text-nowrap">2 star</b>
                <div class="rating-bar-container">
                    <span class="rating-bar" style="width:100.0%"></span>
                </div>
            </div>
            <div class="flex">
                <b class="text-nowrap">1 star</b>
                <div class="rating-bar-container">
                    <span class="rating-bar" style="width:100.0%"></span>
                </div>
            </div>
        </div>
        
    </div>

</div>
<hr>
<div class="row">
    <div class="col-3">
        <p>Reviews</p>
    </div>
    <div class="col-3">
        <form action="" id="usrform" >
            <input style="margin-bottom:20px;" type="text" name="usrname" placeholder="enter username" required /> 
        <br>
          <textarea rows="4" cols="50" name="comment" form="usrform" required>plz add your comments here... </textarea>   
          <input type="submit">
        </form>
    </div>

</div>

</div>  
</div>

<script>
  $(document).ready(function(){
 
    $("#more").hide();
    
  });
  $("#show").click(function(){
      $('#show').hide();
    $("#more").show();
  });
  $("#hide").click(function(){
    $("#more").hide();
    $('#show').show();
    
  });

</script>



<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Find a tutor</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'styles/home.css' %}">

    if Arts.html 
    <link rel="stylesheet" href="{% static 'styles/arts.css' %}"/>
    
    if detail.html
    <link rel="stylesheet" href="{% static 'styles/details.css' %}"/> 
    
    if tutorprofile.html 
    <link rel="stylesheet" href="{%static 'styles/tutorprofile.css' %}"/> 
    
    if registration.html 
    <link rel="stylesheet" href="{%static 'styles/registration.css' %}"/>
    
    if signup.html 
    <link rel="stylesheet" href="{%static 'styles/signup.css' %}"/>

    if login.html 
    <link rel="stylesheet" href="{%static 'styles/login.css' %}"/>

    if resetpassword.html 
    <link rel="stylesheet" href="{%static 'styles/resetpassword.css' %}" />

    if thankyou.html
    <link rel="stylesheet" href="{%static 'styles/thankyou.css' %}" />
</head>
<html>
<body>
<div class='container-fluid'>
      
    
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
      <!-- Brand -->
      <a class="navbar-brand" href="#">Tutors</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <!-- Links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "onlinetutors:tutorprofile" %}">Become an instructor</a>
        </li> 
    
        <!-- Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            Find a tutor
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Music</a>
            <a class="dropdown-item" href="#">Dance</a>
            <a class="dropdown-item" href="#">Theatre</a>
            <a class="dropdown-item" href="{% url "onlinetutors:Arts" %}">Arts</a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item" style="color:white;margin-top:8px;">Hello {{user.username}}</li>
          <li class="nav-item">
          <a class="nav-link" href="{% url "account:logout" %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{% url "account:login" %}">Login</a>
          </li>
          {% endif %}
          <li class="nav-item">
              <a class="nav-link" href="{% url "account:signup" %}">SignUp</a>
          </li>
         
      </ul>
        </div>
    </nav>
</div>
<div class="containerHome">
<div class="background text-center">
    <label for="searchtutors"></label>
    <div class="mainsearch">
      <input type="search" id="tutors" class="text-center" name="tutors" placeholder="Search tutors">
      <!-- <input type="submit" id="submit" class="btn btn-success" onClick="tutors()" value="Submit"><i class="fa fa-search"></i> -->
      <button type="submit" onClick="tutors()" class="submit_button"><i class="fa fa-search"></i></button>
    </div>
</div>

<div class="second-row">
  <h6 class="text-center" style="color: green;font-family:Verdana, Geneva, Tahoma, sans-serif;padding-top:15px;font-weight:1">FIND YOUR TEACHERS FROM</h6>
  <ul class="university_list text-center">
    <li>University of California</li>
    <li>Queen's University</li>
    <li>Yale</li>
    <li>Princeton University</li>
    <hr>
  </ul>

</div>

<div class="third-row">
    <h5 class="text-center" style="padding-top:40px;color:black;font:bold;font-family:'Times New Roman', Times, serif;">HOW  TEACHER4TUTOR  WORKS?</h5>
    <div class="row" style="margin-top:30px;">
      
        <div class="col-4">
          <div class="card" style="width:250px;margin-left:500px;">
            <div class="card-title" style="padding:20px;font-weight:bold;">
              1.Select your exam
            </div>
            <div class="card-text" style="padding-left:20px;padding-bottom:20px;">
              Tell us what you need help with and our
              smart matching system will connect you
              with an online tutor.
          </div>
          </div>
        </div>
        <div class="col-4">
          <div class="card" style="width:250px;margin-left:150px;">
            <div class="card-title" style="padding:20px;font-weight:bold;">
              2.Select your date
            </div>
            <div class="card-text" style="padding-left:20px;padding-bottom:20px;">
              Select when is your exam date then our
              smart matching system will connect you
              with an online tutor.
          </div>
          </div>
        </div>
        <div class="col-4">
          <div class="card" style="width:250px;margin-left:-200px;">
            <div class="card-title" style="padding:20px;font-weight:bold;">
              3.Select your teacher
            </div>
            <div class="card-text" style="padding-left:20px;padding-bottom:20px;">
              Get live 1-on-1 help in our advanced
              lesson space. Use a virtual whiteboard,
              audio/video chat, screen sharing, text
              editor and much more.
          </div>
          </div>
        </div>
    </div>
      
    
  </div>

<p id="demo"></p>
<script>

     function tutors(){
       var x=document.getElementById('tutors').value;
       if (x=='Arts'){
        /*document.location.href="http://127.0.0.1:8000/Arts/"; */
        window.location.href = '/Arts';
       }
       else if(x=='Music'){
        document.location.href="/Music";
      }
      else if(x=='Theatre'){
        document.location.href="/Theatre";
      }
      else if(x=='Dance'){
        document.location.href="/Dance";
      }
       else{
        document.open();
        document.write("<h1>Plz enter a valid search</h1>");
        document.close();
       }
     }

</script>
</div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script> 

</body>
</html>
    

templates/thankyou.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/thankyou.css' %}">
{% endblock %}
{% block content %}
<body>
    <div class="container jumbotron">
        <h3>Thanks for your registration,we will contact you soon!!!</h3>

    </div>
</body>
{% endblock %}